# Generated by Django 5.0.6 on 2025-05-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('price_syp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_image', models.ImageField(upload_to='laptop_main_images/')),
                ('cpu', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=50)),
                ('hdd', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=255)),
                ('screen', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('windows_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='laptop_images/')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.laptop')),
            ],
        ),
    ]
