# Generated by Django 5.0.6 on 2025-06-05 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
                ('url1', models.URLField(blank=True)),
                ('url2', models.URLField(blank=True)),
                ('url3', models.URLField(blank=True)),
                ('url4', models.URLField(blank=True)),
                ('url5', models.URLField(blank=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.producttype')),
            ],
        ),
    ]
