# Generated by Django 5.0.6 on 2025-06-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(choices=[('جديد', 'جديد'), ('مستعمل', 'مستعمل'), ('اوبن بوكس', 'اوبن بوكس')], max_length=20),
        ),
    ]
