# Generated by Django 5.0.6 on 2025-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarPrice',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('dollar_price', models.FloatField()),
            ],
        ),
    ]
