# Generated by Django 5.0.6 on 2025-06-07 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_dollarprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollarprice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
