# Generated by Django 5.0.6 on 2025-06-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='url1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='url2',
            field=models.URLField(blank=True),
        ),
    ]
