# Generated by Django 5.0.6 on 2025-06-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_offer_image1_offer_image2_offer_image3_offer_image4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offer',
        ),
    ]
