# Generated by Django 5.0.6 on 2025-06-11 21:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('url1', models.URLField(blank=True)),
                ('url2', models.URLField(blank=True)),
            ],
        ),
    ]
